import type { Pet, Owner, Appointment, MedicalRecord } from './types'

export const mockOwners: Owner[] = [
  {
    id: 'owner-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    fullName: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '(555) 123-4567',
    address: '123 Oak Street, Springfield, IL 62701',
    petIds: ['pet-1', 'pet-2'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'owner-2',
    firstName: 'Michael',
    lastName: 'Chen',
    fullName: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '(555) 234-5678',
    address: '456 Maple Ave, Springfield, IL 62702',
    petIds: ['pet-3'],
    createdAt: '2024-02-20T14:30:00Z',
  },
  {
    id: 'owner-3',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    fullName: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    phone: '(555) 345-6789',
    address: '789 Pine Road, Springfield, IL 62703',
    petIds: ['pet-4', 'pet-5'],
    createdAt: '2024-03-10T09:15:00Z',
  },
  {
    id: 'owner-4',
    firstName: 'David',
    lastName: 'Thompson',
    fullName: 'David Thompson',
    email: 'david.thompson@email.com',
    phone: '(555) 456-7890',
    address: '321 Elm Court, Springfield, IL 62704',
    petIds: ['pet-6'],
    createdAt: '2024-04-05T16:45:00Z',
  },
]

export const mockPets: Pet[] = [
  {
    id: 'pet-1',
    name: 'Max',
    species: 'dog',
    breed: 'Golden Retriever',
    dateOfBirth: '2020-03-15',
    weight: 32,
    ownerId: 'owner-1',
    profileId: 'owner-1',
    notes: 'Friendly and energetic. Loves treats.',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'pet-2',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Siamese',
    dateOfBirth: '2019-08-22',
    weight: 4.5,
    ownerId: 'owner-1',
    profileId: 'owner-1',
    notes: 'Indoor cat. Slightly anxious during visits.',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'pet-3',
    name: 'Buddy',
    species: 'dog',
    breed: 'Labrador Retriever',
    dateOfBirth: '2021-05-10',
    weight: 28,
    ownerId: 'owner-2',
    profileId: 'owner-2',
    notes: 'Very playful. Up to date on all vaccinations.',
    createdAt: '2024-02-20T14:30:00Z',
  },
  {
    id: 'pet-4',
    name: 'Luna',
    species: 'cat',
    breed: 'Maine Coon',
    dateOfBirth: '2022-01-08',
    weight: 6,
    ownerId: 'owner-3',
    profileId: 'owner-3',
    notes: 'Long-haired, needs regular grooming.',
    createdAt: '2024-03-10T09:15:00Z',
  },
  {
    id: 'pet-5',
    name: 'Tweety',
    species: 'bird',
    breed: 'Parakeet',
    dateOfBirth: '2023-04-12',
    weight: 0.03,
    ownerId: 'owner-3',
    profileId: 'owner-3',
    notes: 'Healthy appetite. Sings frequently.',
    createdAt: '2024-03-10T09:15:00Z',
  },
  {
    id: 'pet-6',
    name: 'Rocky',
    species: 'dog',
    breed: 'German Shepherd',
    dateOfBirth: '2018-11-30',
    weight: 38,
    ownerId: 'owner-4',
    profileId: 'owner-4',
    notes: 'Senior dog. Monitor joints and mobility.',
    createdAt: '2024-04-05T16:45:00Z',
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: 'appt-1',
    petId: 'pet-1',
    ownerId: 'owner-1',
    date: '2026-01-21',
    time: '09:00',
    type: 'checkup',
    status: 'confirmed',
    notes: 'Annual wellness check',
    veterinarian: 'Dr. Amanda Foster',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'appt-2',
    petId: 'pet-3',
    ownerId: 'owner-2',
    date: '2026-01-21',
    time: '10:30',
    type: 'vaccination',
    status: 'scheduled',
    notes: 'Rabies booster due',
    veterinarian: 'Dr. James Wilson',
    createdAt: '2026-01-12T14:00:00Z',
  },
  {
    id: 'appt-3',
    petId: 'pet-4',
    ownerId: 'owner-3',
    date: '2026-01-21',
    time: '14:00',
    type: 'grooming',
    status: 'in-progress',
    notes: 'Full grooming session',
    veterinarian: 'Lisa Martinez',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'appt-4',
    petId: 'pet-6',
    ownerId: 'owner-4',
    date: '2026-01-22',
    time: '11:00',
    type: 'follow-up',
    status: 'scheduled',
    notes: 'Joint assessment follow-up',
    veterinarian: 'Dr. Amanda Foster',
    createdAt: '2026-01-18T16:00:00Z',
  },
  {
    id: 'appt-5',
    petId: 'pet-2',
    ownerId: 'owner-1',
    date: '2026-01-23',
    time: '15:30',
    type: 'checkup',
    status: 'scheduled',
    notes: 'Dental check recommended',
    veterinarian: 'Dr. James Wilson',
    createdAt: '2026-01-19T11:00:00Z',
  },
]

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'record-1',
    petId: 'pet-1',
    appointmentId: 'appt-1',
    date: '2025-01-15',
    type: 'vaccination',
    title: 'Annual Vaccinations',
    description: 'Administered DHPP and Bordetella vaccines. No adverse reactions observed.',
    veterinarian: 'Dr. Amanda Foster',
    createdAt: '2025-01-15T10:30:00Z',
  },
  {
    id: 'record-2',
    petId: 'pet-1',
    date: '2025-06-20',
    type: 'diagnosis',
    title: 'Minor Ear Infection',
    description: 'Diagnosed with otitis externa in left ear. Prescribed Otibiotic ointment for 10 days.',
    veterinarian: 'Dr. James Wilson',
    createdAt: '2025-06-20T14:00:00Z',
  },
  {
    id: 'record-3',
    petId: 'pet-2',
    date: '2025-03-10',
    type: 'vaccination',
    title: 'FVRCP Vaccine',
    description: 'Annual FVRCP vaccination administered. Cat was slightly nervous but cooperative.',
    veterinarian: 'Dr. Amanda Foster',
    createdAt: '2025-03-10T11:00:00Z',
  },
  {
    id: 'record-4',
    petId: 'pet-3',
    date: '2025-05-05',
    type: 'procedure',
    title: 'Dental Cleaning',
    description: 'Professional dental cleaning performed under sedation. Removed mild tartar buildup. No extractions needed.',
    veterinarian: 'Dr. James Wilson',
    createdAt: '2025-05-05T09:00:00Z',
  },
  {
    id: 'record-5',
    petId: 'pet-6',
    date: '2025-08-12',
    type: 'diagnosis',
    title: 'Hip Dysplasia Assessment',
    description: 'X-rays confirm mild hip dysplasia. Recommended joint supplements and weight management.',
    veterinarian: 'Dr. Amanda Foster',
    createdAt: '2025-08-12T15:00:00Z',
  },
  {
    id: 'record-6',
    petId: 'pet-6',
    date: '2025-10-01',
    type: 'prescription',
    title: 'Joint Supplement Prescription',
    description: 'Prescribed Cosequin DS for ongoing joint support. Recheck in 3 months.',
    veterinarian: 'Dr. Amanda Foster',
    createdAt: '2025-10-01T10:00:00Z',
  },
]
